version: '3.8'
services:
  mysql:
    image: mysql:8
    container_name: mysqlCoordinadora    
    restart: always
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password
    ports:
      - ${MYSQL_PORT}:${MYSQL_DOCKER_PORT}
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d

  redis:
    image: redis
    container_name: redisCoordinadora
    restart: always
    env_file: ./.env
    ports:
      - ${REDIS_PORT}:${REDIS_DOCKER_PORT}
    depends_on:
      - mysql      

  api:
    build: .
    container_name: apiCoordinadora
    restart: always
    env_file: ./.env
    environment:
      IS_DOCKER: "true"
    ports:
      - ${SERVER_PORT}:${SERVER_DOCKER_PORT}
    depends_on:
      - mysql
      - redis
    links:
      - mysql
      - redis
  
